// Thin Resend wrapper. Guarded: if RESEND_API_KEY is unset, sending is a no-op
// that reports `skipped` — so invite-link generation works before email is
// connected. When the key is added, the same calls start delivering.

import { BRAND_NAME } from '@/lib/brand'
// M5: re-exported so the existing `from '@/lib/email'` import sites keep
// working; the implementation lives in lib/html.ts, dependency-free so it can
// be unit-tested directly.
export { escapeHtml } from '@/lib/html'
import { escapeHtml } from '@/lib/html'

export interface SendResult {
  id?: string
  skipped?: boolean
  error?: string
}

const FROM = process.env.RESEND_FROM ?? 'Simvites <onboarding@resend.dev>'

export function emailConfigured() {
  return !!process.env.RESEND_API_KEY
}

export async function sendEmail(opts: {
  to: string
  subject: string
  html: string
}): Promise<SendResult> {
  if (!emailConfigured()) return { skipped: true }

  try {
    const res = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${process.env.RESEND_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ from: FROM, to: opts.to, subject: opts.subject, html: opts.html }),
    })
    const data = (await res.json()) as { id?: string; message?: string }
    if (!res.ok) return { error: data.message ?? `Resend error ${res.status}` }
    return { id: data.id }
  } catch (e) {
    return { error: e instanceof Error ? e.message : 'send failed' }
  }
}

export function invitationEmailHtml(opts: {
  siteName: string
  householdName: string
  link: string
}) {
  const siteName = escapeHtml(opts.siteName)
  const householdName = escapeHtml(opts.householdName)
  // The link is minted server-side from a hashed token, but escape it too:
  // it sits inside an href attribute, and "generated by us" is a property that
  // quietly stops being true the moment someone refactors this.
  const link = escapeHtml(opts.link)
  // Brand design language: warm ivory, ink text, one terracotta accent, serif.
  return `
  <div style="background:#fbf9f5;padding:36px 16px">
    <div style="font-family:Georgia,'Times New Roman',serif;max-width:520px;margin:0 auto;background:#ffffff;border:1px solid #e8e2d8;border-radius:13px;padding:36px;color:#2a241d">
      <p style="font-family:Consolas,monospace;letter-spacing:.2em;text-transform:uppercase;font-size:11px;color:#8a8072;margin:0">${siteName}</p>
      <h1 style="font-weight:400;font-size:32px;line-height:1.1;margin:10px 0 18px">You're invited.</h1>
      <p style="font-size:16px;line-height:1.65;margin:0 0 8px">Dear ${householdName},</p>
      <p style="font-size:16px;line-height:1.65;margin:0">We would be honoured to celebrate with you. Open your personal invitation to see your events and let us know you're coming.</p>
      <p style="margin:30px 0">
        <a href="${link}" style="background:#b4552d;color:#fff;text-decoration:none;padding:13px 30px;border-radius:9px;font-weight:600;font-size:15px">Open your invitation</a>
      </p>
      <p style="font-size:12.5px;color:#8a8072;line-height:1.6">This link is personal to your household — please don't forward it.<br>If the button doesn't work, paste this into your browser:<br><span style="word-break:break-all">${link}</span></p>
    </div>
    <p style="font-family:Consolas,monospace;text-align:center;letter-spacing:.18em;text-transform:uppercase;font-size:10px;color:#a49a8a;margin-top:18px">Made with ${BRAND_NAME}</p>
  </div>`
}
